### ISSUE TITLE
asterisk command not found

### ISSUE THREAD

**Issue by zeeshankhan** [leedm777/homebrew-asterisk#17]
Hi,

I did the installation as per the README file, and below are the last three lines of installation process before making directory.

> Warning: asterisk dependency gettext was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.
> 🍺  /usr/local/Cellar/asterisk/13.3.2: 1047 files, 40M, built in 2.8 minutes

After running both `mkdir` command, I tried running `asterisk -c` and got the `command not found` error.

 When i tried running it from the `/usr/local/Cellar/asterisk/13.3.2` directory, i got below error:

> Airtel:sbin Zeeshan$ sudo ./asterisk -c
Password:
Asterisk 13.3.2, Copyright (C) 1999 - 2014, Digium, Inc. and others.
Created by Mark Spencer <markster@digium.com> 
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details. This is free software, with components licensed under the GNU General Public License version 2 and other licenses; you are welcome to redistribute it under certain conditions. Type 'core show license' for details.

> [ Initializing Custom Configuration Options ]
Unable to load config file 'stasis.conf'
Could not load Stasis configuration; using defaults
[May 15 17:39:06] NOTICE[1287]: features_config.c:1842 int load_config(): Could not load features config; using defaults
[May 15 17:39:06] NOTICE[1287]: cdr.c:4053 int process_config(int): Failed to process CDR configuration; using defaults
[May 15 17:39:06] NOTICE[1287]: cdr.c:4156 int cdr_toggle_runtime_options(): CDR simple logging enabled.
[May 15 17:39:06] NOTICE[1287]: udptl.c:1316 void __ast_udptl_reload(int): Could not load udptl config; using defaults
[May 15 17:39:06] NOTICE[1287]: cel.c:1768 int ast_cel_engine_init(): Failed to process CEL configuration; using defaults
[May 15 17:39:06] NOTICE[1287]: manager.c:8693 int __init_manager(int, int): Unable to open AMI configuration manager.conf, or configuration is invalid.
asterisk(51968,0x7fff750b7310) malloc: *** error for object 0x102211e40: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Mac OS: Mavericks 10.9.5
Please provide some guidance here. Many Thanks.

**Comment by leedm777** [comment]
The command's not found b/c asterisk installs into the `sbin` directory instead of `bin`. Try `/usr/local/sbin/asterisk`, or adding `/usr/local/sbin` to your path.

Aside from `chan_vpb`, Asterisk doesn't use C++, so the different `libc++` shouldn't be a problem.

The other issue may be because you don't have any configuration files. There are steps in the README for adding some, but they don't look quite right.

**Comment by zeeshankhan** [comment]
I've couple of questions:
1. Why did asterisk get install on `sbin`?
2. Why are we creating `/usr/local/Cellar/asterisk/` directory 

I also didn't understand below line from you comment.
> Aside from `chan_vpb`, Asterisk doesn't use C++, so the different `libc++` shouldn't be a problem.

There is no such directory called `asterisk ` in `sbin`, its actually a binary file. 
Even after adding the path `/usr/local/sbin`, asterisk command didn't work from the `sbin`  directory and I'm getting the same error as mentioned earlier. 
The error says:
> Unable to load config file 'stasis.conf'
> Could not load Stasis configuration; using defaults

and other files are not getting loaded when running `sudo ./asterisk` command from `sbin`.

**Comment by leedm777** [comment]
> 1. Why did asterisk get install on sbin?

That's just what Asterisk does. I have no idea why. It's done that at least [since May of 2001](https://github.com/asterisk/asterisk/commit/7e5ebff4c45abbbdbe5d0eae555f71bd74190b0b), so I doubt that's going to change.

> 2. Why are we creating /usr/local/Cellar/asterisk/ directory

That's where [Homebrew installs packages](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md).

> I also didn't understand below line from you comment.

That's in response to the warning in your issue report.

> There is no such directory called asterisk in sbin, its actually a binary file. 

Yes. Asterisk installs it's executable into `sbin` instead of `bin`.

> Even after adding the path /usr/local/sbin, asterisk command didn't work from the sbin directory and I'm getting the same error as mentioned earlier.

Two problems. The first is that you don't have a configuration. I pushed an update on Friday to install sample configs, so that should be better.

The second problem is that I'm seeing Asterisk crash immediately on startup, even with the config files in place. I haven't been able to track that one down yet.

**Comment by leedm777** [comment]
I've reverted the build to use GCC, and that works around the problem. Building with clang is very new, and is probably buggy.

Please update and try again.

**Comment by zeeshankhan** [comment]
Thank you so much for your quick replies.
I tried setting up asterisk using centOS 6 through virtual box and it worked for me.
I'll give this one another try sometime.
Thanks again.
Cheers :+1:
