### ISSUE TITLE
Facing issue with WebRTC

### ISSUE THREAD

**Issue by prashantd** [leedm777/homebrew-asterisk#19]
Hi,

I am able to make normal calls but when I try to enable WebRTC using SIP.js, I get the following error:
WebSocket connection to 'ws://192.168.1.73:8088/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

Do I need to change anything in the http.conf file?

Thanks.

**Comment by leedm777** [comment]
Probably. More details on using WebRTC with Asterisk can be found [on the wiki](https://wiki.asterisk.org/wiki/display/AST/Asterisk+WebRTC+Support).

Since this doesn't seem to be a problem specific to the homebrew build of Asterisk, if you need further help getting WebRTC working, you can ask on the [#asterisk IRC channel or the asterisk-users mailing list](http://www.asterisk.org/community/discuss).
